apiVersion: v1
kind: Service
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
